version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data
  db:
    image: docker.io/library/mariadb:10
    restart: unless-stopped
    volumes:
      - ${PAPERLESS_HOST_ROOT_FOLDER}/dbdata:/var/lib/mysql
    env_file:
      - .env
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - 8001:8000
    volumes:
      - ${PAPERLESS_HOST_ROOT_FOLDER}/data:/usr/src/paperless/data
      - ${PAPERLESS_HOST_ROOT_FOLDER}/media:/usr/src/paperless/media
      - ${PAPERLESS_HOST_ROOT_FOLDER}/export:/usr/src/paperless/export
      - ${PAPERLESS_HOST_ROOT_FOLDER}/consume:/usr/src/paperless/consume
    env_file:
      - .env
  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.10
    restart: unless-stopped
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - gotenberg
      - --chromium-disable-javascript=true
      - --chromium-allow-list=file:///tmp/.*
  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped
  db_backup_paperless:
    container_name: paperless_db_backup
    image: tiredofit/db-backup
    depends_on:
      - db
    volumes:
      - /home/daniel/stacks/backups/nextcloud/mysql_db/:/backup
      #- ./post-script.sh:/assets/custom-scripts/post-script.sh
    env_file:
      - .env
volumes:
  redisdata: null
networks: {}
